CREATE TABLE IF NOT EXISTS FS_NOTIFICATION (
    NOTIFICATION_ID     VARCHAR(36) NOT NULL,
    CLIENT_ID           VARCHAR(255) NOT NULL,
    RESOURCE_ID         VARCHAR(255) NOT NULL,
    STATUS              VARCHAR(10) NOT NULL,
    UPDATED_TIMESTAMP   BIGINT NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID)
);

CREATE TABLE IF NOT EXISTS FS_NOTIFICATION_EVENT (
    EVENT_ID            INT(11) NOT NULL AUTO_INCREMENT,
    NOTIFICATION_ID     VARCHAR(36) NOT NULL,
    EVENT_TYPE          VARCHAR(200) NOT NULL,
    EVENT_INFO          VARCHAR(1000) NOT NULL,
    PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_NotificationEvent FOREIGN KEY (NOTIFICATION_ID) REFERENCES FS_NOTIFICATION(NOTIFICATION_ID)
);

CREATE TABLE IF NOT EXISTS FS_NOTIFICATION_ERROR (
    NOTIFICATION_ID     VARCHAR(36) NOT NULL,
    ERROR_CODE          VARCHAR(255) NOT NULL,
    DESCRIPTION         VARCHAR(255) NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID),
    CONSTRAINT FK_NotificationError FOREIGN KEY (NOTIFICATION_ID) REFERENCES FS_NOTIFICATION(NOTIFICATION_ID)
);

CREATE TABLE IF NOT EXISTS FS_NOTIFICATION_SUBSCRIPTION (
    SUBSCRIPTION_ID     VARCHAR(36) NOT NULL,
    CLIENT_ID           VARCHAR(255) NOT NULL,
    REQUEST             CLOB NOT NULL,
    CALLBACK_URL        VARCHAR(255),
    TIMESTAMP           BIGINT NOT NULL,
    SPEC_VERSION        VARCHAR(255),
    STATUS              VARCHAR(255) NOT NULL,
    PRIMARY KEY (SUBSCRIPTION_ID)
);

CREATE TABLE IF NOT EXISTS FS_NOTIFICATION_SUBSCRIBED_EVENTS (
    SUBSCRIPTION_ID     VARCHAR(36) NOT NULL,
    EVENT_TYPE          VARCHAR(255) NOT NULL,
    PRIMARY KEY (SUBSCRIPTION_ID, EVENT_TYPE),
    CONSTRAINT FK_NotificationSubEvents FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES FS_NOTIFICATION_SUBSCRIPTION(SUBSCRIPTION_ID)
);
