CREATE TABLE IF NOT EXISTS OB_THROTTLE_DATA (
    THROTTLE_GROUP VARCHAR(100) NOT NULL,
    THROTTLE_PARAM VARCHAR(100) NOT NULL,
    LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNLOCK_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OCCURRENCES INTEGER NOT NULL,
    PRIMARY KEY (THROTTLE_GROUP,THROTTLE_PARAM)
);
