CREATE OR REPLACE PROCEDURE WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP IS


rowCount INT;
CURRENT_SCHEMA VARCHAR(100);
-- ------------------------------------------
-- CONFIGURABLE ATTRIBUTES
-- ------------------------------------------
enableLog BOOLEAN := TRUE; -- ENABLE LOGGING [DEFAULT : TRUE]
logLevel VARCHAR(10):= 'TRACE'; -- SET LOG LEVELS : TRACE


BEGIN

SELECT SYS_CONTEXT( 'USERENV', 'CURRENT_SCHEMA' ) INTO CURRENT_SCHEMA FROM DUAL;

IF (enableLog)
THEN
    SELECT COUNT(*) INTO rowCount from ALL_TABLES where OWNER = CURRENT_SCHEMA AND table_name = upper('LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP');
    IF (rowCount = 1) then
    EXECUTE IMMEDIATE 'DROP TABLE LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP';
    COMMIT;
    END if;
    EXECUTE IMMEDIATE 'CREATE TABLE LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP VARCHAR(250) , LOG VARCHAR(250)) NOLOGGING';
    COMMIT;
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP STARTED .... !'')';
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),'' '')';
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''USING SCHEMA :'||CURRENT_SCHEMA||''')';
    COMMIT;
END IF;


-- ---------------------

SELECT COUNT(1) INTO rowCount FROM ALL_TABLES where OWNER = CURRENT_SCHEMA AND TABLE_NAME IN ('FS_NOTIFICATION');
IF (rowCount = 1)
THEN
    IF (enableLog AND logLevel IN ('TRACE')) THEN
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''CLEANUP DATA RESTORATION STARTED ON FS_NOTIFICATION TABLE !'')';
    COMMIT;
    END IF;
    EXECUTE IMMEDIATE 'INSERT INTO FS_NOTIFICATION SELECT A.* FROM BAK_FS_NOTIFICATION A LEFT JOIN FS_NOTIFICATION B ON A.NOTIFICATION_ID = B.NOTIFICATION_ID WHERE B.NOTIFICATION_ID IS NULL';
    rowCount:=  sql%Rowcount;
    IF (enableLog ) THEN
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''CLEANUP DATA RESTORATION COMPLETED ON FS_NOTIFICATION WITH '||rowCount||''')';
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),'' '')';
    COMMIT;
    END IF;
END IF;

-- ---------------------

SELECT COUNT(1) INTO rowCount FROM ALL_TABLES where OWNER = CURRENT_SCHEMA AND TABLE_NAME IN ('FS_NOTIFICATION_EVENT');
IF (rowCount = 1)
THEN
    IF (enableLog AND logLevel IN ('TRACE')) THEN
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''CLEANUP DATA RESTORATION STARTED ON FS_NOTIFICATION_EVENT TABLE !'')';
    COMMIT;
    END IF;
    EXECUTE IMMEDIATE 'INSERT INTO FS_NOTIFICATION_EVENT SELECT A.* FROM BAK_FS_NOTIFICATION_EVENT A LEFT JOIN FS_NOTIFICATION_EVENT B ON A.NOTIFICATION_ID = B.NOTIFICATION_ID WHERE B.NOTIFICATION_ID IS NULL';
    rowCount:=  sql%Rowcount;
    IF (enableLog ) THEN
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''CLEANUP DATA RESTORATION COMPLETED ON FS_NOTIFICATION_EVENT WITH '||rowCount||''')';
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),'' '')';
    COMMIT;
    END IF;
END IF;

-- ---------------------

SELECT COUNT(1) INTO rowCount FROM ALL_TABLES where OWNER = CURRENT_SCHEMA AND TABLE_NAME IN ('FS_NOTIFICATION_ERROR');
IF (rowCount = 1)
THEN
    IF (enableLog AND logLevel IN ('TRACE')) THEN
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''CLEANUP DATA RESTORATION STARTED ON FS_NOTIFICATION_ERROR TABLE !'')';
    COMMIT;
    END IF;
    EXECUTE IMMEDIATE 'INSERT INTO FS_NOTIFICATION_ERROR SELECT A.* FROM BAK_FS_NOTIFICATION_ERROR A LEFT JOIN FS_NOTIFICATION_ERROR B ON A.NOTIFICATION_ID = B.NOTIFICATION_ID WHERE B.NOTIFICATION_ID IS NULL';
    rowCount:=  sql%Rowcount;
    IF (enableLog ) THEN
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''CLEANUP DATA RESTORATION COMPLETED ON FS_NOTIFICATION_ERROR WITH '||rowCount||''')';
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),'' '')';
    COMMIT;
    END IF;
END IF;

-- ---------------------

IF (enableLog)
THEN
    EXECUTE IMMEDIATE 'INSERT INTO LOG_WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP (TIMESTAMP,LOG) VALUES (TO_CHAR( SYSTIMESTAMP, ''DD.MM.YYYY HH24:MI:SS:FF4''),''WSO2_FS_EVENT_NOTIFICATION_CLEANUP_DATA_RESTORE_SP COMPLETED .... !'')';
    COMMIT;
END IF;

END;
