CREATE TABLE IF NOT EXISTS OB_ACCOUNT_METADATA (
    ACCOUNT_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    METADATA_KEY VARCHAR(100) NOT NULL,
    METADATA_VALUE VARCHAR(100) NOT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (USER_ID,ACCOUNT_ID,METADATA_KEY)
);
